### ISSUE TITLE
Add a Refresh button allowing user to manually refresh job status if needed

### ISSUE THREAD

**Issue by zhiyuli** [cybergis/job-supervisor-python-sdk#15]
It seems Jupyter kernel may "sleep" and SDK UI may get stuck if there is a long compute job runs on HPC.
A workaround would be add a "Refresh" button to the SDK UI allowing user to manually refresh job status if needed.

**Comment by alexandermichels** [comment]
Should be closed with https://github.com/cybergis/cybergis-compute-python-sdk/pull/20, but we will need to test.
