### ISSUE TITLE
Allow to retrieve model results after SDK session dies

### ISSUE THREAD

**Issue by zhiyuli** [cybergis/job-supervisor-python-sdk#16]
Users might not wait for long-running job submission and the notebook session may die (computer goes into sleep mode or browser is closed).  Or in some cases, the SDK UI stops updating job status due to bugs or something else.

Assume user knows job_id, we need a way for user to check job status and retrieve model results in a new notebook session.

I wrote up a notebook for emergency use to handle this case (upon request from a user). But this notebook is NOT user-friendly.
https://github.com/cybergis/cybergis-compute-v2-wrfhydro/blob/main/retrieve_model_outputs.ipynb

It is better to add a new function to the SDK that can take a job_id, display (re-activate) the job status UI, and allow to download results.

**Comment by alexandermichels** [comment]
Should be resolved by https://github.com/cybergis/cybergis-compute-python-sdk/pull/20, but needs testing.

**Comment by alexandermichels** [comment]
@zhiyuli think we can close this? Anything else needed?
