### ISSUE TITLE
Failing to set `jupyterhubHost` variable when Javascript is not supported (for e.g JupyterLab)

### ISSUE THREAD

**Issue by mitkotak** [cybergis/job-supervisor-python-sdk#27]
## Issue 

SDK is not able to find ``JUPYTER_INSTANCE_URL`` in JupyterLab environments and even if it can, it does not support Javascript to capture the variable as done  [here](https://github.com/cybergis/cybergis-compute-python-sdk/blob/11c5c6fd2a00e75e274bc1d6f965c9252e736dd9/cybergis_compute_client/CyberGISCompute.py#L497)

## Solution

Allow the user to specify jupyterhost ip and port and migrate to service url instead of jupyter instance url

## RoadMap

if enable_jupyter raises some kind of javascript exception then prompt the user to enter the url and port similar to [`login`](https://github.com/cybergis/cybergis-compute-python-sdk/blob/11c5c6fd2a00e75e274bc1d6f965c9252e736dd9/cybergis_compute_client/CyberGISCompute.py#L69)

**Comment by mitkotak** [comment]
@zimo-xiao @alexandermichels  Let me know if this makes sense. Thanks !

**Comment by alexandermichels** [comment]
@mitkotak Did this ever get resolved? It seems that #34 addresses it, but I wanted to verify before closing.

**Comment by mitkotak** [comment]
Yup it's resolved.
