### ISSUE TITLE
Cancel Button missing in SDK

### ISSUE THREAD

**Issue by mitkotak** [cybergis/job-supervisor-python-sdk#30]
## Issue

SDK currently does not support ability to cancel a job. This can be an issue for users who might accidentally submit a job that they want to cancel

## Solution

The proposed solution requires changes in core and sdk

### Core

- Add ```job/:jobId/delete_job``` path in ```server.ts```
- The validation code will be identical ```job/:jobId/create_job```
- Create ```supervisor.popJobFromQueue(job)``` similar to ```supervisor.pushJobToQueue(job)```  inside ```src/Supervisor.ts```
- Create```this.queues[job.hpc].pop(job)``` similar to```this.queues[job.hpc].push(job)``` ( Would this change only support removal of recently submitted jobs ) ?
- Create ```pop(item: Job)``` similar to ```push(item:Job)``` inside ```src/Queue.ts```
- Modify ```redis.conf``` to support job poping

### SDK 

- Add ```delete``` which makes a call to ```/job/:jobId/delete``` similar to ```submit```
- In UI create ```renderDelete``` and ```onDeleteButtonClick```

**Comment by alexandermichels** [comment]
Requires implementation in the Core first: https://github.com/cybergis/cybergis-compute-core/blob/v2/server.ts#L852

**Comment by alexandermichels** [comment]
Solved by:
* https://github.com/cybergis/cybergis-compute-core/pull/93 on the Core side
* https://github.com/cybergis/cybergis-compute-python-sdk/pull/72 on the SDK side

Getting an actual cancel button was difficult, but appropriate docs were added.
