### ISSUE TITLE
Your Jobs tab page to show model name

### ISSUE THREAD

**Issue by zhiyuli** [cybergis/job-supervisor-python-sdk#43]
It seems the "Your Jobs" tab page currently does not show the model name. So users can not know what model it is

This happens on current V2 (tag 2.1) branch, not sure if this is a regression issue.

<img width="743" alt="image" src="https://user-images.githubusercontent.com/10070599/184709714-c9ab54a2-074e-42f4-abf5-c8fdc130a6f6.png">

**Comment by taylorziegler** [comment]
I added the model name to the "Your Jobs" tab. Let me know if this looks okay https://github.com/cybergis/cybergis-compute-python-sdk/pull/44.

**Comment by alexandermichels** [comment]
I merged #44 and it seems to be working. @zhiyuli please check if it works with the latest version of the SDK and reply back. The model name is now the last element in the second row, but if that's a big issue we can move it.

**Comment by alexandermichels** [comment]
#44 seems to have solved the issue
