### ISSUE TITLE
[Bug] random 504 error when downloading results back to jupyter via globus

### ISSUE THREAD

**Issue by zhiyuli** [cybergis/job-supervisor-python-sdk#46]
This is a random error message on the client side that may happen during downloading model results back to jupyter using globus.
The symptom is SDK throws out a 504 bad gateway error. After rerun the show_ui cell and restore the job, it shows the globus downloading is still going though globus downloading has been done (I could see the result files on jupyter). The consequence is download path attribute of SDK object is None affecting some cells below that depend on its value. and you can not re-download the results again as it always show downloading is still going.

I just registered this issue here and will try to post more error messages when it happens again (if any).
As far I can tell this is NOT a new issue I remember it happened several times months ago, but we did not get a chance to investigate the root. 

Probable case might be on the core side where globus job status stops being tracked and updated due to some errors

**Comment by alexandermichels** [comment]
Any idea how we might replicate this? Any advice to someone who might run into it?

**Comment by alexandermichels** [comment]
We haven't had more reports of this issue since it was opened so closing. Please reopen if we get an example.
