### ISSUE TITLE
UI test with JupyterLab

### ISSUE THREAD

**Issue by zhiyuli** [cybergis/job-supervisor-python-sdk#6]

**Comment by alexandermichels** [comment]
UI looks good to me on JuypterLab for the Hello World job and job runs. Anything more specific we need to check to prepare for the transition?

![JupyterLabUI](https://user-images.githubusercontent.com/36479843/171256661-b5efc9ce-f95a-48f9-a17e-4fb0de146438.png)

**Comment by alexandermichels** [comment]
The rows were running too long without a scroll bar. That should be fixed by https://github.com/cybergis/cybergis-compute-python-sdk/pull/28
