### ISSUE TITLE
[Feature Request] Sort models in Job Templates dropdown

### ISSUE THREAD

**Issue by fbaig** [cybergis/job-supervisor-python-sdk#87]
## Feature Request
Sort list of models (alphabetically?) in Job Templates dropdown in the UI.

**Is your feature request related to a problem? Please describe.**
Not sure how current list of models is sorted in existing UI dropdown. However, it would be visually nice if the list of models can be sorted alphabetically. Especially important since the number of models are increasing.

**Describe the solution you'd like**
Self explanatory

**Describe alternatives you've considered**
Not sure how the models are sorted currently. Open to other ideas as well but should be intuitive enough considering our user base.

**Comment by alexandermichels** [comment]
It's addressed in #79 we just need to package it up and put it out on Pypi. Will probably do that at end of semester once we have a few other PRs wrapped up.

**Comment by fbaig** [comment]
Great. Is there a milestone with respect to that so this can be closed when done?

**Comment by alexandermichels** [comment]
Not yet, but great suggestion! I'll set up one up and tie this issue to it.

**Comment by alexandermichels** [comment]
Fixed in new release
